# **<u>Sales Dataset Cleaning</u>**

In [1]:
import pandas as pd
data = pd.read_excel('C:/Users/HP/Downloads/supermarket_sales.xlsx')

In [2]:
data.to_csv('sales_uncleaned.csv', index=False)

## *Looking at the whole dataset*

In [3]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

In [4]:
#from IPython.display import display
#display(data)

## *Checking our data*

In [5]:
print(data.shape)

(1000, 17)

In [6]:
data.describe()

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,0.000000,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905,49.650000,10.00000

## *Checking for missing values*

In [7]:
print(data.isnull().sum())

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

## *Checking for duplicates*

In [8]:
print(data.duplicated().sum())

0

# *Checking data types*

In [9]:
print(data.dtypes)

Invoice ID                     str
Branch                         str
City                           str
Customer type                  str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Total                      float64
Date                        object
Time                        object
Payment                        str
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [10]:
data['Date'] =pd.to_datetime(data['Date'])
#Changing the data type of date so that we can be able to extract year, month and day from the data easily

# *Removing whitespaces in strings*

In [11]:
data = data.apply(lambda col: col.str.strip() if pd.api.types.is_string_dtype(col) else col)

## *Formatting Dates*

In [12]:
data['Date'] = pd.to_datetime(data['Date'], errors = 'coerce')
data['Date'] = data['Date'].dt.strftime('%Y-%m-%d')

# *Removing useless columns*

In [13]:
data.drop(columns=["gross margin percentage"], inplace=True)

# *Fix the time column*

In [14]:
def parse_time_to_seconds(time_str):
    parts = str(time_str).split(':')
    minutes = int(parts[0])
    seconds = int(parts[1])
    milliseconds = int(parts[2])
    total_seconds = minutes * 60 + seconds + milliseconds / 1000
    return total_seconds

data['time_sec'] = data['Time'].apply(parse_time_to_seconds)

In [15]:
data.drop(columns = 'Time', inplace = True)

In [16]:
data.dtypes

Invoice ID           str
Branch               str
City                 str
Customer type        str
Gender               str
Product line         str
Unit price       float64
Quantity           int64
Tax 5%           float64
Total            float64
Date                 str
Payment              str
cogs             float64
gross income     float64
Rating           float64
time_sec         float64
dtype: object

## *Creating the day and month columns*

In [17]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Now extract day and month
data['day'] = data['Date'].dt.day_name()
data['month'] = data['Date'].dt.month_name()

In [18]:
data.columns
data.head(20)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Payment,cogs,gross income,Rating,time_sec,day,month
0,692-92-5582,B,Mandalay,Member,Female,Food_and_beverages,54.84,3,8.2260,172.7460,2019-02-20,Credit card,164.52,8.2260,5.9,807.0,Wednesday,February
1,351-62-0822,B,Mandalay,Member,Female,Fashion_accessories,14.48,4,2.8960,60.8160,2019-06-02,Ewallet,57.92,2.8960,4.5,1087.0,Sunday,June
2,529-56-3974,B,Mandalay,Member,Male,Electronic_accessories,25.51,4,5.1020,107.1420,2019-09-03,Cash,102.04,5.1020,6.8,1023.0,Tuesday,September
3,299-46-1805,B,Mandalay,Member,Female,Sports_and_travel,93.72,6,28.1160,590.4360,2019-01-15,Cash,562.32,28.1160,4.5,979.0,Tuesday,January
4,319-50-3348,B,Mandalay,Normal,Female,Home_and_lifestyle,40.30,2,4.0300,84.6300,2019-11-03,Ewallet,80.60,4.0300,4.4,930.0,Sunday,November
5,371-85-5789,B,Mandalay,Normal,Male,Health_and_beauty,87.98,3,13.1970,277.1370,2019-05-03,Ewallet,263.94,13.1970,5.1,640.0,Friday,May
6,273-16-6619,B,Mandalay,Normal,Male,Home_and_lifestyle,33.20,2,3.3200,69.7200,2019-03-15,Credit card,66.40,3.3200,4.4,740.0,Friday,March
7,649-29-6775,B,Mandalay,Normal,Male,Fashion_accessories,33.52,1,1.6760,35.1960,2019-08-02,Cash,33.52,1.6760,6.7,931.0,Friday,August
8,145-94-9061,B,Mandalay,Normal,Female,Food_and_beverages,88.36,5,22.0900,463.8900,2019-01-25,Cash,441.80,22.0900,9.6,1188.0,Friday,January
9,871-79-8483,B,Mandalay,Normal,Male,Fashion_accessories,94.13,5,23.5325,494.1825,2019-02-25,Credit card,470.65,23.5325,4.8,1179.0,Monday,February
10,149-71-6266,B,Mandalay,Member,Male,Sports_and_travel,78.07,9,35.1315,737.7615,2019-01-28,Cash,702.63,35.1315,4.5,763.0,Monday,January
11,640-49-2076,B,Mandalay,Normal,Male,Sports_and_travel,83.78,8,33.5120,703.7520,2019-10-01,Cash,670.24,33.5120,5.1,889.0,Tuesday,October
12,777-82-7220,B,Mandalay,Member,Male,Home_and_lifestyle,30.12,8,12.0480,253.0080,2019-03-03,Cash,240.96,12.0480,7.7,781.0,Sunday,March
13,280-35-5823,B,Mandalay,Member,Female,Home_and_lifestyle,86.72,1,4.3360,91.0560,2019-01-17,Ewallet,86.72,4.3360,7.9,1125.0,Thursday,January
14,354-25-5821,B,Mandalay,Member,Female,Sports_and_travel,69.12,6,20.7360,435.4560,2019-08-02,Cash,414.72,20.7360,5.6,783.0,Friday,August
15,132-32-9879,B,Mandalay,Member,Female,Electronic_accessories,93.96,4,18.7920,394.6320,2019-09-03,Cash,375.84,18.7920,9.5,1080.0,Tuesday,September
16,370-41-7321,B,Mandalay,Member,Male,Health_and_beauty,56.69,9,25.5105,535.7205,2019-02-27,Credit card,510.21,25.5105,8.4,1044.0,Wednesday,February
17,727-46-3608,B,Mandalay,Member,Female,Food_and_beverages,20.01,9,9.0045,189.0945,2019-06-02,Ewallet,180.09,9.0045,4.1,947.0,Sunday,June
18,669-54-1719,B,Mandalay,Member,Male,Electronic_accessories,18.93,6,5.6790,119.2590,2019-10-02,Credit card,113.58,5.6790,8.1,765.0,Wednesday,October
19,616-24-2851,B,Mandalay,Member,Female,Fashion_accessories,17.87,4,3.5740,75.0540,2019-03-22,Ewallet,71.48,3.5740,6.5,882.0,Friday,March

In [19]:
data.to_csv("sales_cleaned.csv", index=False)